In [1]:
from lxml import etree
import urllib.request
import urllib.parse
import pandas as pd
import unicodedata

In [13]:
def query(content):
    # 请求地址
    url = content
    # 请求头部
    headers = { 
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' 
    }
    # 利用请求地址和请求头部构造请求对象
    req = urllib.request.Request(url = url, headers = headers, method = 'GET')
    # 发送请求，获得响应
    try:
        response = urllib.request.urlopen(req)
        # 读取响应，获得文本
        text = response.read().decode('utf-8')
        # 构造 _Element 对象
        html = etree.HTML(text)
        # 使用 xpath 匹配数据，得到 <div class="mw-parser-output"> 下所有的子节点对象
        obj_list = html.xpath('//div[@class="mw-parser-output"]/*')
        
        #获取<h2>节点对象
        find = False
        start_h2 = 0
        end_h2 = 0
        for i in range(len(obj_list)):
            if 'h2'==obj_list[i].tag:
                if obj_list[i].xpath('.//text()')[0] == 'Playing style':
                    find = True
                    start_h2 = i+1
                    continue
            if 'h2'==obj_list[i].tag and find:
                    end_h2 = i-1
            if end_h2!=0:
                break

        if not find:
            return ""
        playing_style_p = obj_list[start_h2:end_h2+1]
        playing_style_p_list = [obj.xpath('.//text()') for obj in playing_style_p]
        playing_style = [p.encode('utf-8').decode() for playing_style in playing_style_p_list for p in playing_style]
        playing_style_after_filter = [item.strip('\n') for item in playing_style]
        
        
        return ''.join(playing_style_after_filter)
    except:
        pass

In [26]:
content = "https://en.wikipedia.org/wiki/Brian_Gottfried"
#content = "https://en.wikipedia.org/wiki/Denis_Shapovalov"
result= query(content)
result

''

In [14]:
import pandas as pd
female_df = pd.read_csv('wta_df_female.csv')
female_name = list(female_df['winner_name'])+list(female_df['loser_name'])
female_name = list(set(female_name))

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (8,16) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [17]:
male_df = pd.read_csv('atp_df_male.csv')
male_name = list(male_df['winner_name'])+list(male_df['loser_name'])
male_name = list(set(male_name))

In [15]:
#players = ['Maria Sharapova', 'Svetlana Kuznetsova', 'Jelena Jankovic', 'Yanina Wickmayer', 'Sara Errani', 'Francesca Schiavone', 'Iveta Benesova', 'Petra Kvitova', 'Angelique Kerber', 'Ana Ivanovic', 'Lucie Safarova', 'Christina Mchale', 'Serena Williams', 'Dominika Cibulkova', 'Daniela Hantuchova', 'Samantha Stosur', 'Jarmila Gajdosova', 'Tsvetana Pironkova', 'Shahar Peer', 'Agnieszka Radwanska', 'Irina Camelia Begu', 'Na Li', 'Jie Zheng', 'Galina Voskoboeva', 'Shuai Peng', 'Caroline Wozniacki', 'Roberta Vinci', 'Nadia Petrova', 'Su Wei Hsieh', 'Maria Kirilenko', 'Sofia Arvidsson', 'Anabel Medina Garrigues', 'Ksenia Pervak', 'Carla Suarez Navarro', 'Victoria Azarenka', 'Simona Halep', 'Julia Goerges', 'Lucie Hradecka', 'Mona Barthel', 'Aleksandra Wozniak', 'Urszula Radwanska', 'Chanelle Scheepers', 'Alize Cornet', 'Sorana Cirstea', 'Monica Niculescu', 'Kaia Kanepi', 'Klara Koukalova', 'Flavia Pennetta', 'Petra Cetkovska', 'Marina Erakovic', 'Kate Makarova', 'Varvara Lepchenko', 'Tamira Paszek', 'Venus Williams', 'Sabine Lisicki', 'Polona Hercog', 'Anastasia Pavlyuchenkova', 'Vera Zvonareva', 'Sloane Stephens', 'Kim Clijsters', 'Yaroslava Shvedova', 'Marion Bartoli', 'Barbora Strycova', 'Andrea Petkovic', 'Maria Jose Martinez Sanchez', 'Petra Martic', 'Kirsten Flipkens', 'Laura Robson', 'Heather Watson', 'Elena Vesnina', 'Annika Beck', 'Karin Knapp', 'Elina Svitolina', 'Bojana Jovanovski', 'Bethanie Mattek Sands', 'Kristina Mladenovic', 'Monica Puig', 'Magdalena Rybarikova', 'Jamie Hampton', 'Lourdes Dominguez Lino', 'Madison Keys', 'Eugenie Bouchard', 'Kiki Bertens', 'Ayumi Morita', 'Romina Oprandi', 'Stefanie Voegele', 'Aravane Rezai', 'Timea Bacsinszky', 'Patty Schnyder', 'Alexandra Dulgheru', 'Johanna Larsson', 'Rebecca Marino', 'Agnes Szavay', 'Alisa Kleybanova', 'Anastasija Sevastova', 'Greta Arn', 'Anna Chakvetadze', 'Gisela Dulko', 'Justine Henin', 'Alona Bondarenko', 'Melanie Oudin', 'Elena Dementieva', 'Sybille Bammer', 'Melinda Czink', 'Kateryna Bondarenko', 'Virginie Razzano', 'Elena Baltacha', 'Vera Dushevina', 'Olga Govortsova', 'Dinara Safina', 'Arantxa Parra Santonja', 'Shuai Zhang', 'Yvonne Meusburger', 'Kurumi Nara', 'Garbine Muguruza', 'Karolina Pliskova', 'Camila Giorgi', 'Belinda Bencic', 'Alison Riske Amritraj', 'Casey Dellacqua', 'Caroline Garcia', 'Zarina Diyas', 'Coco Vandeweghe', 'Maria Teresa Torro Flor', 'Lauren Davis', 'Anna Karolina Schmiedlova', 'Alison Van Uytvanck', 'Madison Brengle', 'Johanna Konta', 'Teliana Pereira', 'Daria Saville', 'Lesia Tsurenko', 'Elise Mertens', 'Anett Kontaveit', 'Kristyna Pliskova', 'Qiang Wang', 'Daria Kasatkina', 'Mirjana Lucic', 'Oceane Dodin', 'Catherine Cartan Bellis', 'Ana Konjuh', 'Laura Siegemund', 'Misaki Doi', 'Naomi Osaka', 'Katerina Siniakova', 'Jelena Ostapenko', 'Yulia Putintseva', 'Timea Babos', 'Ashleigh Barty', 'Maria Sakkari', 'Shelby Rogers', 'Danka Kovinic', 'Margarita Gasparyan', 'Anna Lena Friedsam', 'Pauline Parmentier', 'Donna Vekic', 'Mihaela Buzarnescu', 'Danielle Collins', 'Aliaksandra Sasnovich', 'Aryna Sabalenka', 'Aleksandra Krunic', 'Elena Rybakina', 'Veronika Kudermetova', 'Dayana Yastremska', 'Saisai Zheng', 'Viktoria Kuzmova', 'Ekaterina Alexandrova', 'Amanda Anisimova', 'Sofia Kenin', 'Ajla Tomljanovic', 'Bianca Andreescu', 'Karolina Muchova', 'Magda Linette', 'Marketa Vondrousova', 'Yafan Wang', 'Iga Swiatek', 'Ons Jabeur', 'Cori Gauff', 'Nadia Podoroska', 'Jennifer Brady', 'Fiona Ferro', 'Marie Bouzkova', 'Jessica Pegula', 'Barbora Krejcikova', 'Jil Teichmann', 'Paula Badosa', 'Sara Sorribes Tormo', 'Tamara Zidansek', 'Viktorija Golubic', 'Liudmila Samsonova', 'Leylah Fernandez', 'Clara Tauson', 'Emma Raducanu', 'Ann Li', 'Rebecca Peterson', 'Marta Kostyuk', 'Tereza Martincova', 'Camila Osorio', 'Jasmine Paolini', 'Anhelina Kalinina', 'Nuria Parrizas Diaz', 'Mayar Sherif', 'Beatriz Haddad Maia', 'Martina Trevisan', 'Anna Bondar', 'Qinwen Zheng']
players = female_name
players1 = []
for p in players:
    temp = p.split(" ")
    players1.append("_".join(temp))

path = 'https://en.wikipedia.org/wiki/'
path_ps = '/Users/mia/Desktop/ISE540/project/player_style_female/'
for i,p in enumerate(players1):
    txt = query(path + p)
    if not txt:
        continue
    file = open(path_ps + players[i] + '.txt', mode = 'w')
    file.write(txt)
    file.close()

In [18]:
players = male_name
players1 = []
for p in players:
    temp = p.split(" ")
    players1.append("_".join(temp))

path = 'https://en.wikipedia.org/wiki/'
path_ps = '/Users/mia/Desktop/ISE540/project/player_style_male/'
for i,p in enumerate(players1):
    txt = query(path + p)
    if not txt:
        continue
    file = open(path_ps + players[i] + '.txt', mode = 'w')
    file.write(txt)
    file.close()

## connect data with topic

In [9]:
topic_women = pd.read_csv('f_document_topic.csv')
wta_df_female = pd.read_csv('women_atp.csv')

In [10]:
wta_df_female_combine=pd.merge(wta_df_female,topic_women, left_on='winner_name', right_on='Name', how='left')
d = ['Topic0','Topic1','Topic2','Topic3','Topic4','Topic5','Topic6','Topic7','Name']
for col in wta_df_female_combine.columns:
    if col in d:
        del wta_df_female_combine[col]
wta_df_female_combine=wta_df_female_combine.rename(columns = {'topic':'winner_topic'})
wta_df_female_combine1=pd.merge(wta_df_female_combine,topic_women, left_on='loser_name', right_on='Name', how='left')

In [11]:
wta_df_female_combine1

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_name,winner_hand,...,winner_topic,Name,Topic0,Topic1,Topic2,Topic3,Topic4,Topic5,Topic6,topic
0,2012-W-INT-AUS-01A-2012,Hobart,Hard,32,I,20120109,1,201518,Yanina Wickmayer,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2012-W-INT-AUS-01A-2012,Hobart,Hard,32,I,20120109,2,201348,Casey Dellacqua,L,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2012-W-INT-AUS-01A-2012,Hobart,Hard,32,I,20120109,4,201593,Irina Camelia Begu,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2012-W-INT-AUS-01A-2012,Hobart,Hard,32,I,20120109,5,201403,Anna Chakvetadze,R,...,6.0,Monica Niculescu,0.03,0.03,0.79,0.03,0.03,0.04,0.03,2.0
4,2012-W-INT-AUS-01A-2012,Hobart,Hard,32,I,20120109,6,201450,Tsvetana Pironkova,R,...,6.0,Heather Watson,0.03,0.03,0.80,0.03,0.03,0.03,0.03,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29632,2022-W-FC-2022-QLS-M-ROU-POL-01,BJK Cup QLS R1: ROU vs POL,Hard,4,D,20220415,3,216347,Iga Swiatek,R,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29633,2022-W-FC-2022-QLS-M-USA-UKR-01,BJK Cup QLS R1: USA vs UKR,Hard,4,D,20220415,1,201590,Alison Riske Amritraj,R,...,NaN,Dayana Yastremska,0.02,0.91,0.02,0.02,0.02,0.02,0.02,1.0
29634,2022-W-FC-2022-QLS-M-USA-UKR-01,BJK Cup QLS R1: USA vs UKR,Hard,4,D,20220415,2,202468,Jessica Pegula,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29635,2022-W-FC-2022-QLS-M-USA-UKR-01,BJK Cup QLS R1: USA vs UKR,Hard,4,D,20220415,3,215035,Dayana Yastremska,R,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29636,2022-W-FC-2022-QLS-M-USA-UKR-01,BJK Cup QLS R1: USA vs UKR,Hard,4,D,20220415,4,215290,Katarina Zavatska,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
wta_df_female_combine1=pd.merge(wta_df_female_combine,topic_women, left_on='loser_name', right_on='Name', how='left')
for col in wta_df_female_combine1.columns:
    if col in d:
        del wta_df_female_combine1[col]

In [13]:
wta_df_female_combine1=wta_df_female_combine1.rename(columns = {'topic':'loser_tpoic'})
wta_df_female_combine1.to_csv("women_atp_combine.csv")

---------------

In [21]:
import pandas as pd
topic_women = pd.read_csv('m_document_topic.csv')
wta_df_female = pd.read_csv('men_atp.csv')

In [22]:
wta_df_female_combine=pd.merge(wta_df_female,topic_women, left_on='winner_name', right_on='Name', how='left')
d = ['Topic0','Topic1','Topic2','Topic3','Topic4','Topic5','Topic6','Topic7','Name']
for col in wta_df_female_combine.columns:
    if col in d:
        del wta_df_female_combine[col]
wta_df_female_combine=wta_df_female_combine.rename(columns = {'topic':'winner_topic'})
wta_df_female_combine1=pd.merge(wta_df_female_combine,topic_women, left_on='loser_name', right_on='Name', how='left')

In [23]:
#wta_df_female_combine1=pd.merge(wta_df_female_combine,topic_women, left_on='loser_name', right_on='Name', how='left')
for col in wta_df_female_combine1.columns:
    if col in d:
        del wta_df_female_combine1[col]

In [24]:
wta_df_female_combine1=wta_df_female_combine1.rename(columns = {'topic':'loser_topic'})

In [81]:
wta_df_female_combine1.to_csv("men_atp_combine.csv")

In [25]:
wta_df_female_combine1

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_name,winner_hand,...,l_1stWon,l_2ndWon,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,winner_topic,loser_topic
0,2010-339,Brisbane,Hard,32,A,20100103,28,103285,Radek Stepanek,R,...,25.0,11.0,6.0,10.0,12.0,2625.0,105.0,521.0,3.0,NaN
1,2010-339,Brisbane,Hard,32,A,20100103,16,103285,Radek Stepanek,R,...,14.0,10.0,1.0,6.0,12.0,2625.0,306.0,137.0,3.0,NaN
2,2010-339,Brisbane,Hard,32,A,20100103,17,104053,Andy Roddick,R,...,26.0,18.0,7.0,8.0,7.0,4410.0,134.0,400.0,7.0,NaN
3,2010-339,Brisbane,Hard,32,A,20100103,18,104755,Richard Gasquet,R,...,22.0,9.0,3.0,6.0,52.0,850.0,285.0,151.0,3.0,NaN
4,2010-339,Brisbane,Hard,32,A,20100103,20,105064,Thomaz Bellucci,L,...,39.0,18.0,3.0,5.0,36.0,1021.0,119.0,461.0,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30665,2022-560,Us Open,Hard,128,G,20220829,199,111575,Karen Khachanov,R,...,35.0,28.0,10.0,15.0,31.0,1315.0,53.0,879.0,NaN,NaN
30666,2022-560,Us Open,Hard,128,G,20220829,198,105807,Pablo Carreno Busta,R,...,52.0,27.0,5.0,10.0,15.0,2340.0,20.0,1665.0,NaN,1.0
30667,2022-560,Us Open,Hard,128,G,20220829,197,106401,Nick Kyrgios,R,...,37.0,13.0,6.0,11.0,25.0,1430.0,87.0,610.0,NaN,NaN
30668,2022-560,Us Open,Hard,128,G,20220829,114,207733,Jack Draper,L,...,34.0,7.0,0.0,5.0,53.0,879.0,49.0,956.0,NaN,NaN
30669,2022-560,Us Open,Hard,128,G,20220829,177,144895,Corentin Moutet,L,...,48.0,14.0,2.0,8.0,112.0,484.0,22.0,1573.0,NaN,NaN